# Configuration for Train Tickets

# Tickets settings
 tickets:
   default: unlimited
   permissions:
     give: superexpress.ticket.give
   configurable_material: "<Material_Name>"
   default_custom_name: "<Ticket_Name>"
   timed:
     enabled: true
     countdown: 30  # duration in seconds
   reset_speed_when_not_held: true
